banner:
# æ ‡é¢˜æ 
  enable: true
  title:
    - æ˜æ˜
    - é“­
    - æ˜
    - é“­
    - ã®
    - å°ç«™
  src: /js/ui/banner.js
  border: true
  # æ˜¯å¦å¼€å¯æ ‡è¯­ä¸­å­—ç¬¦çš„å·¦å³è¾¹æ¡†
  cloud:
  # åœ¨é¦–é¡µä¸‹æ–¹æ˜¾ç¤ºæµåŠ¨çš„äº‘
    enable: true
    color: "white"
  go_down:
  # å‘ä¸‹ç®­å¤´æŒ‰é’®ï¼ˆç‚¹å‡»ç¿»é¡µï¼‰
    enable: true
    icon: icon-arrow-down-s-line

notice:
# å…¬å‘Š
  enable: false
  content: æ¬¢è¿å…‰ä¸´ï¼

mode: auto
# é»‘æš—æ¨¡å¼å¼€å…³

social:
# ç¤¾äº¤å›¾æ ‡
  - name: QQ
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://wpa.qq.com/msgrd?v=3&uin=1779036876&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/zjm54321
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:1779036876@qq.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/412244715
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: Telegram
    link: https://t.me/Zjmmmm
    icon: icon-telegram-line
    color: "#0088CC"
  - name: RSS
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange

trianglify:
# èƒŒæ™¯
  enable: true
  cellSize: 75
  width: 1920
  height: 1080
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

avatar:
# ä¾§è¾¹æ 
  enable: true
  url: https://cdn.jsdelivr.net/gh/zjm54321/pictures/avater.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ

footer:
# é¡µçœ‰
  since: 2020
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
  powered:
    enable: true
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2021-01-19T00:00:00"

#algolia_search:
# æœç´¢
#  enable: true
#  src: /js/search/algolia-search.js
#  hits:
#    per_page: 10
local_search:
  enable: true

wordcount:
# å­—æ•°ç»Ÿè®¡
  enable: true
  count: true
  time: true

girls:
# æ ‡ç­¾
  enable: false

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue


menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: icon-clipboard-line

wordcloud:
  enable: true

baidu_push: true

google_analytics:
  enable: true
  id: G-EHXMM70MZZ

google_adsense:
  enable: true
  client: ca-pub-7109020926751133

#valine:
#  enable: true
#  appId: o768CG8RBDuGUSnno1kAfhLf-gzGzoHsz
#  appKey: 8u3Q2jloRlspntbhlMqcUX08
#  placeholder: Just go go # 
#  avatar: 
#  meta:
#    - nick
#    - mail
#    - link
#  pageSize: 10 
#  highlight: true
#  recordIP: true
#  enableQQ: true
minivaline:
  enable: false
  md: true
  # æ›´å¤šé€‰é¡¹ https://minivaline.js.org/docs/cn/#/Options æŒ‰ç…§ymlæ ¼å¼ç»§ç»­å¡«å†™å³å¯ ï¼ˆé™¤äº† [el] é€‰é¡¹ï¼‰
  # emoticonUrl ç­‰åˆ—è¡¨é€‰é¡¹ å¯å‚è€ƒ https://github.com/MiniValine/hexo-next-minivaline
  # ä¸‹é¢æ˜¯ä¸€ä¸ªä¾‹å­ï¼š
  backend: waline
  serverURL: https://mini-valine-two.vercel.app/

github_issues:
  enable: false

github_discussions:
  enable: false

comment:
  tips:
    - å¦‚æœæ‚¨æœ‰ä»»ä½•å…³äºåšå®¢å†…å®¹çš„ç›¸å…³è®¨è®ºï¼Œæ¬¢è¿åœ¨è¯„è®ºåŒºä¸æˆ‘äº¤æµã€‚

reward:
  enable: true
  icon: icon-hand-coin-line
  comment: æˆ‘ï¼Œç§¦å§‹çš‡ï¼Œæ‰“é’±ï¼Œæ‡‚ï¼Ÿ[doge]
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.jsdelivr.net/gh/zjm54321/pictures/alipay_money.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/zjm54321/pictures/qq_money.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/zjm54321/pictures/wx_money.png
      color: "#2DC100"
      icon: icon-wechat-pay-linee

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

live2d:
  enable: true
  # æ¨èä½¿ç”¨ jsdelivr çš„ CDN æ¥åŠ è½½
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    # æ¨èä½¿ç”¨ CDN æ¥åŠ è½½æ¨¡å‹
    use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
  # dialog:
  #   # æ˜¯å¦å¼€å¯å¯¹è¯æ¡†
  #   enable: true
  #   # æ˜¯å¦ä½¿ç”¨ä¸€è¨€
  #   hitokoto: true
